// Generated by typings
// Source: node_modules/angularfire2/angularfire2.d.ts
declare module '~firebase.app.module/angularfire2' {
import { FirebaseAppConfigToken, FirebaseApp } from '~firebase.app.module/firebase.app.module';
import { InjectionToken } from '@angular/core';
import { Subscription } from 'rxjs/Subscription';
export interface FirebaseAppConfig {
    apiKey?: string;
    authDomain?: string;
    databaseURL?: string;
    storageBucket?: string;
    messagingSenderId?: string;
    projectId?: string;
}
const FirebaseAppName: InjectionToken<string>;
export const FirebaseAppProvider: {
    provide: typeof FirebaseApp;
    useFactory: (config: FirebaseAppConfig, appName?: string | undefined) => FirebaseApp;
    deps: InjectionToken<FirebaseAppConfig>[];
};
export class AngularFireModule {
    static initializeApp(config: FirebaseAppConfig, appName?: string): {
        ngModule: typeof AngularFireModule;
        providers: ({
            provide: InjectionToken<FirebaseAppConfig>;
            useValue: FirebaseAppConfig;
        } | {
            provide: InjectionToken<string>;
            useValue: string | undefined;
        })[];
    };
}
export class ZoneScheduler {
    zone: any;
    constructor(zone: any);
    schedule(...args: any[]): Subscription;
}
export { FirebaseApp, FirebaseAppName, FirebaseAppConfigToken };
}
declare module 'firebase.app.module/angularfire2' {
export * from '~firebase.app.module/angularfire2';
}

// Generated by typings
// Source: node_modules/angularfire2/public_api.d.ts
declare module '~firebase.app.module/public_api' {
export * from '~firebase.app.module/angularfire2';
}
declare module 'firebase.app.module/public_api' {
export * from '~firebase.app.module/public_api';
}

// Generated by typings
// Source: node_modules/angularfire2/index.d.ts
declare module '~firebase.app.module/index' {
export * from '~firebase.app.module/public_api';
export { _firebaseAppFactory as ɵa } from '~firebase.app.module/firebase.app.module';
}
declare module 'firebase.app.module/index' {
export * from '~firebase.app.module/index';
}

// Generated by typings
// Source: node_modules/angularfire2/firebase.app.module.d.ts
declare module '~firebase.app.module/firebase.app.module' {
import { InjectionToken } from '@angular/core';
import { FirebaseAppConfig } from '~firebase.app.module/index';
import * as firebase from 'firebase/app';
export const FirebaseAppConfigToken: InjectionToken<FirebaseAppConfig>;
export class FirebaseApp implements firebase.app.App {
    name: string;
    options: {};
    auth: () => firebase.auth.Auth;
    database: () => firebase.database.Database;
    messaging: () => firebase.messaging.Messaging;
    storage: () => firebase.storage.Storage;
    delete: () => firebase.Promise<any>;
}
export function _firebaseAppFactory(config: FirebaseAppConfig, appName?: string): FirebaseApp;
}
declare module 'firebase.app.module/firebase.app.module' {
export * from '~firebase.app.module/firebase.app.module';
}
declare module 'firebase.app.module' {
export * from '~firebase.app.module/firebase.app.module';
}
